#
# Copyright (c) 2025 Huawei Technologies Co., Ltd. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM quay.io/ascend/vllm-ascend:v0.11.0-openeuler

ARG PIP_INDEX_URL="https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
ARG SOC_VERSION=Ascend910B3

ENV LMCACHE_TRACK_USAGE=false

RUN pip config set global.index-url ${PIP_INDEX_URL}

WORKDIR /workspace

COPY . /workspace/LMCache-Ascend/

# Install LMCache
RUN NO_CUDA_EXT=1 pip install lmcache==0.3.12

# Install LMCache-Ascend
RUN cd /workspace/LMCache-Ascend && \
    export CPLUS_INCLUDE_PATH=/usr/include/c++/12:/usr/include/c++/12/`uname -i`-openEuler-linux:$CPLUS_INCLUDE_PATH && \
    export SOC_VERSION=${SOC_VERSION} && \
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/Ascend/ascend-toolkit/latest/`uname -i`-linux/devlib && \
    python3 -m pip install -v --no-build-isolation -e . && \
    python3 -m pip cache purge

CMD ["/bin/bash"]


